service: docker-plus
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListAllMyBuckets'
          Resource: '*'
        # Allow functions to create buckets
        - Effect: Allow
          Action: 's3:CreateBucket'
          Resource: '*'
plugins:
  - serverless-offline

functions:
  api:
    handler: ./src/index.hello
    events:
      - httpApi:
          path: /
          method: get
  create:
    handler: ./src/index.create
    events:
      - httpApi:
          path: /
          method: post
    
